### ISSUE TITLE
Limiter is broken (still)

### ISSUE THREAD

**Issue by Lucas9810** [KaleidonKep99/OmniConverter#10]
This was the result of using the limiter on bad apple betelgeuse mode (with 100k voices on all tracks)
It is way too quiet on the heavy parts, the beginning has a massive clipping artifact, and the ending of the wave is broken too 
[ba_betelguese_mp3convert.zip](https://github.com/KaleidonKep99/OmniConverter/files/15251853/ba_betelguese_mp3convert.zip)
(this took 3 days of rendering on an OC ryzen 5 lol)

**Comment by KaleidonKep99** [comment]
Fixed by switching back to the latest version of CSCore.
