### ISSUE TITLE
Unlimited voice count option keeps reseting

### ISSUE THREAD

**Issue by Zidon224** [KaleidonKep99/OmniConverter#11]
This setting kepps reseting to default (Disabeld) after I click Ok.
I also checked settings.json and I couldn't find any setting related to unlimited voice count.
I used the linux build.
Here are more specs about my computer where I ran OC...
![image](https://github.com/KaleidonKep99/OmniConverter/assets/92180085/30044f8a-0b70-4b65-80ab-e51aa2f5c200)

**Comment by KaleidonKep99** [comment]
Fixed in the Avalonia release!
I will release binaries shortly.
