### ISSUE TITLE
Timer in OmniConverter while processing being too quickly.

### ISSUE THREAD

**Issue by Hu63Dovella** [KaleidonKep99/OmniConverter#19]
I started to process a MIDI at approximately 5:30, and at 21:15, it writes 16h40 as time elapsed. (Expected 15h45.)
A method to fix: Use time module.

**Comment by KaleidonKep99** [comment]
![image](https://github.com/user-attachments/assets/ff51fd42-48cc-4665-b85e-caa2c39d53fb)
