### ISSUE TITLE
Exporting each track separately instead of merging leads to uncorrectable clipping

### ISSUE THREAD

**Issue by Lucas9810** [KaleidonKep99/OmniConverter#2]
Setting OmniConverter to enable multi-threaded export, render each track of a MIDI separately, and Export each track separately instead of merging them automatically _and_ disabling the audio limiter results in .WAV files that contain uncorrectable clipping, even if a limiter is used, such as fruity limiter. 

Steps to reproduce: See instructions above
Expected behavior: OmniConverter renders separate audio files that are not clipped and are able to go above 0 DB for easy limiting and audio editing, like in KMC.
Video of problem: https://cdn.discordapp.com/attachments/223264079672770561/858800533413953576/2021-06-27_15-01-11.mp4
Info about the program:
OC 0.0.3 (PR)
Bass 2.4.14 - U27
BassMIDI 2.4.12 - U10
Windows 10 Pro 
Version 2009 / 20H2 x64 (19042)
Ryzen 5 5600x 
64GB DDR4-3600

**Comment by Razzy9270** [comment]
It seems like this also happens to me but even without selecting the track-seperated export it sounds distorted on the latest, even with limiter enabled (Which I am guessing isn't functional in this version). On the previous version, it seems like the limiter is working fine (I've only tested this without the track-seperated export option and the multithreaded midi export option turned on, I'm rendering that one right now).
