### ISSUE TITLE
Use of XSynth

### ISSUE THREAD

**Issue by MyBlackMIDIScore** [KaleidonKep99/OmniConverter#20]
First of all let me say I am really glad to see this project becoming cross platform and improving overall!

I was working today on C bindings for XSynth for a personal project and wanted to share this with you in case you were ever planning to implement other synthesizers in OmniConverter, like you did with OmniMIDIv2. So yeah if this was in your plans then this library might help you a bit. I have also added plenty of documentation to make it easier to understand what the functions are doing and how it works generally.

I also implemented the realtime module in this C library so it can easily be used with OmniMIDIv2 too (since from what I can tell there is no source or any documentation for the DLL being used currently).

The repo: [MyBlackMIDIScore/xsynth-clib](https://github.com/MyBlackMIDIScore/xsynth-clib)

If you have any questions let me know. If you are not interested, feel free to close this issue. :)

**Comment by arduano** [comment]
Side note, should we make an org for all this black midi software that we all usually contribute to together anyway?

**Comment by arduano** [comment]
Or keeping it private is good for your resume ig

**Comment by MyBlackMIDIScore** [comment]
> Side note, should we make an org for all this black midi software that we all usually contribute to together anyway?

Might be useful actually. Up to the you really, my contributions are very small for me to decide that anyway lol

> Or keeping it private is good for your resume ig

Lmao

**Comment by KaleidonKep99** [comment]
Thank you! I'll add this ASAP.
~~I asked Kaydax to add C bindings at first, but he refused to.~~

**Comment by MyBlackMIDIScore** [comment]
Great, glad it helps! If you have any questions or encounter any issues with it, please open an issue (or discussion) on the GH repo because I cannot use Discord atm

**Comment by KaleidonKep99** [comment]
Completed!
