### ISSUE TITLE
Using the "Check for Updates" buttons in OmniConverter result in an error message

### ISSUE THREAD

**Issue by Lucas9810** [KaleidonKep99/OmniConverter#3]
Using the "Check for Updates" button in the information window _or_ the  in OC results in an "Unknown Error".

Steps to reproduce: Open "Information about the driver" in the "?" tab, and press the "check for updates button" or use the "check for updates" button in the "?" tab
Expected behavior: OmniConverter checks for updates as normal, and either downloads a new update or displays a "no updates found" message as normal
Video of problem: https://cdn.discordapp.com/attachments/223264079672770561/858802623159468062/2021-06-27_15-13-18.mp4
Screenshot of the error message: https://media.discordapp.net/attachments/223264079672770561/858802765514014790/unknown.png?width=1259&height=676
Info about the program:
OC 0.0.3 (PR)
Bass 2.4.14 - U27
BassMIDI 2.4.12 - U10
Windows 10 Pro 
Version 2009 / 20H2 x64 (19042)
Ryzen 5 5600x 
64GB DDR4-3600

**Comment by KaleidonKep99** [comment]
Fixed in the Avalonia release!
I will release binaries shortly.
