### ISSUE TITLE
Editing Soundfont list Error

### ISSUE THREAD

**Issue by NyanWhite** [KaleidonKep99/OmniConverter#6]
Removing all soundfont, and then clicking on the blank soundfont list, steadily triggers this Error.
Can this bug be fixed? This problem has been present from the first to the latest version, although it doesn't affect the use too much.
![shot](https://github.com/KaleidonKep99/OmniConverter/assets/51278093/17fbefec-17bb-4d78-998b-fd870881b62c)

**Comment by NyanWhite** [comment]
I've been using Adobe Media Encoder, and it occurred to me that OmniConverter could make converting each MIDI a conversion task like AME, so that it could import the same MIDI over and over again, and export each MIDI with a different parameter for a different selected soundfont. It would also be possible to have a global setting that would be used when a single conversion task is not edited. If this is changed it should be a great help for people who make videos using multi-tone soundfont mixes.
and here's a little idea I had.

**Comment by KaleidonKep99** [comment]
Common SoundFonts support has been removed, since it has been the main cause of issues in the SoundFonts list editor.

So, fixed in the Avalonia release!
I will release binaries shortly.

**Comment by KaleidonKep99** [comment]
> I've been using Adobe Media Encoder, and it occurred to me that OmniConverter could make converting each MIDI a conversion task like AME, so that it could import the same MIDI over and over again, and export each MIDI with a different parameter for a different selected soundfont. It would also be possible to have a global setting that would be used when a single conversion task is not edited. If this is changed it should be a great help for people who make videos using multi-tone soundfont mixes. and here's a little idea I had.

I might add this as an option in the settings. Thank you for the idea!
