### ISSUE TITLE
Compatibility issues with certain soundfonts.

### ISSUE THREAD

**Issue by NTKRNLPA** [KaleidonKep99/OmniConverter#8]
Since several updates, OmniConverter has problems with some Soundfonts, especially in the SFZ format (I have no problems with SF2 yet).

One of the incompatible soundfonts belongs to the SFZ 4.1 implementation format: Cathan Concert Grand 2.1.1 made by MBMS Productions.

Also many MBMS Productions soundfonts in my possession like Roland Master Piano, and MBMS Compact Grand seem to suffer from the same problem.

Regardless of the MIDI, they always output empty files.

And in more particular cases, like the Soundfont "Project CF-162" by Kryomel in it's SFZ version, always output wav files where track 0 is skipped.

Thanks to the recommendations of one of the contributors of this repo, @khang06, I discarded any compatibility issues with the latest BASS versions.

This seems to be a unique OmniConverter problem, and no program using the latest BASS libraries seems to have this problem either, including OmniMIDI.

If you have any questions, feel free to let me know, have a nice day.

**Comment by KaleidonKep99** [comment]
Fixed in the Avalonia release!
I will release binaries shortly.
